CREATE TABLE `articles` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`slug` varchar(191) NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`dekEn` text NOT NULL,
	`dekAr` text NOT NULL,
	`category` enum('public-health','nutrition','mental-health','research','policy') NOT NULL,
	`categoryLabelEn` varchar(100) NOT NULL,
	`categoryLabelAr` varchar(100) NOT NULL,
	`bodyEn` json NOT NULL,
	`bodyAr` json NOT NULL,
	`sourceNameEn` varchar(255) NOT NULL,
	`sourceNameAr` varchar(255) NOT NULL,
	`sourceUrl` varchar(512) NOT NULL DEFAULT '#',
	`publishedAt` varchar(10) NOT NULL,
	`readMins` int NOT NULL DEFAULT 3,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `articles_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `doctors` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`specialtyEn` varchar(255) NOT NULL,
	`specialtyAr` varchar(255) NOT NULL,
	`languages` json NOT NULL,
	`clinicEn` varchar(255) NOT NULL,
	`clinicAr` varchar(255) NOT NULL,
	`cityEn` varchar(100) NOT NULL,
	`cityAr` varchar(100) NOT NULL,
	`phone` varchar(40) NOT NULL,
	`verified` boolean NOT NULL DEFAULT false,
	`bioEn` text NOT NULL,
	`bioAr` text NOT NULL,
	`slots` json NOT NULL,
	`sourceNameEn` varchar(255) NOT NULL,
	`sourceNameAr` varchar(255) NOT NULL,
	`sourceUrl` varchar(512) NOT NULL DEFAULT '#',
	`updateEn` text NOT NULL,
	`updateAr` text NOT NULL,
	`updateSourceEn` varchar(255) NOT NULL,
	`updateSourceAr` varchar(255) NOT NULL,
	`updateDate` varchar(10) NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `doctors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `episodes` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`number` int NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`guestsEn` json NOT NULL,
	`guestsAr` json NOT NULL,
	`airedAt` varchar(10) NOT NULL,
	`durationMins` int NOT NULL,
	`topicsEn` json NOT NULL,
	`topicsAr` json NOT NULL,
	`summaryEn` text NOT NULL,
	`summaryAr` text NOT NULL,
	`notesEn` text NOT NULL,
	`notesAr` text NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `episodes_id` PRIMARY KEY(`id`),
	CONSTRAINT `episodes_number_unique` UNIQUE(`number`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`category` enum('screening','workshop','walk','talk') NOT NULL,
	`date` varchar(10) NOT NULL,
	`timeEn` varchar(100) NOT NULL,
	`timeAr` varchar(100) NOT NULL,
	`cityEn` varchar(100) NOT NULL,
	`cityAr` varchar(100) NOT NULL,
	`venueEn` varchar(255) NOT NULL,
	`venueAr` varchar(255) NOT NULL,
	`hostEn` varchar(255) NOT NULL,
	`hostAr` varchar(255) NOT NULL,
	`free` boolean NOT NULL DEFAULT true,
	`price` int,
	`sourceNameEn` varchar(255) NOT NULL,
	`sourceNameAr` varchar(255) NOT NULL,
	`sourceUrl` varchar(512) NOT NULL DEFAULT '#',
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pharmacies` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`areaEn` varchar(255) NOT NULL,
	`areaAr` varchar(255) NOT NULL,
	`cityEn` varchar(100) NOT NULL,
	`cityAr` varchar(100) NOT NULL,
	`hoursEn` varchar(255) NOT NULL,
	`hoursAr` varchar(255) NOT NULL,
	`onDuty` boolean NOT NULL DEFAULT false,
	`phone` varchar(40) NOT NULL,
	`verified` boolean NOT NULL DEFAULT false,
	`sourceNameEn` varchar(255) NOT NULL,
	`sourceNameAr` varchar(255) NOT NULL,
	`sourceUrl` varchar(512) NOT NULL DEFAULT '#',
	`updateEn` text NOT NULL,
	`updateAr` text NOT NULL,
	`updateSourceEn` varchar(255) NOT NULL,
	`updateSourceAr` varchar(255) NOT NULL,
	`updateDate` varchar(10) NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `pharmacies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `services` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`type` enum('lab','imaging','physio','home-care') NOT NULL,
	`cityEn` varchar(100) NOT NULL,
	`cityAr` varchar(100) NOT NULL,
	`priceFrom` int NOT NULL,
	`providerEn` varchar(255) NOT NULL,
	`providerAr` varchar(255) NOT NULL,
	`sourceNameEn` varchar(255) NOT NULL,
	`sourceNameAr` varchar(255) NOT NULL,
	`sourceUrl` varchar(512) NOT NULL DEFAULT '#',
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `services_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stories` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`authorEn` varchar(255) NOT NULL,
	`authorAr` varchar(255) NOT NULL,
	`cityEn` varchar(100) NOT NULL,
	`cityAr` varchar(100) NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`quoteEn` text NOT NULL,
	`quoteAr` text NOT NULL,
	`excerptEn` text NOT NULL,
	`excerptAr` text NOT NULL,
	`bodyEn` json NOT NULL,
	`bodyAr` json NOT NULL,
	`destination` enum('dead-sea','main-hot-springs','wadi-rum','petra','aqaba'),
	`destinationLabelEn` varchar(255),
	`destinationLabelAr` varchar(255),
	`moodTag` enum('calm','energized','stressed','tired','joyful') NOT NULL,
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`sample` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `users` (
	`id` serial AUTO_INCREMENT NOT NULL,
	`unionId` varchar(255) NOT NULL,
	`name` varchar(255),
	`email` varchar(320),
	`avatar` text,
	`role` enum('user','admin') NOT NULL DEFAULT 'user',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	`lastSignInAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_unionId_unique` UNIQUE(`unionId`)
);
